spring.application.name=fichas-de-internet
spring.datasource.url=jdbc:mysql://localhost:3306/fichas_de_internet
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true